const defaultPlayers = [
  "Ash Hind",
  "Bailey Fulton", 
  "Ben Attle", 
  "Ben Franks",
  "Ben Helliwell",
  "Bradley Travis", 
  "Cameron Thurlow",
  "Chad Ogden", 
  "Craig Ingham", 
  "Danny Minshull", 
  "Dom Johnson", 
  "Jake Halstead",
  "James Shooter", 
  "Joe Duffy", 
  "Joe Kinnear", 
  "Joe Rawlins", 
  "Jorge Westin-Pearson", 
  "Josh Robinson",
  "Kieren Keogh",
  "Kyle Carrington", 
  "Leon Khan", 
  "Liam Mcgee🧤",
  "Luke Masters",
  "Matty Carysforth",
  "Niall Raymond",
  "Reece Kendall",
  "Ross Barney",
  "Seb Jennings",
  "Shed",
  "Sohrob Rostampour", 
  "Tom Kelton", 
  "Tom Wright", 
  "Trevor Jones",
  "Will Allsopp",
  "Zach Murphy",
  "Zak Waddington"
];
