const defaultPlayers = [
  "Bailey Fulton", 
  "Ben Attle", 
  "Ben Franks",
  "Bradley Travis", 
  "Chad Ogden", 
  "Craig Ingham", 
  "Danny Minshull", 
  "Dom Johnson", 
  "Jake Halstead",
  "James Shooter", 
  "Joe Duffy", 
  "Joe Kinnear", 
  "Joe Rawlins", 
  "John Sheard (Shed)", 
  "Jorge Westin-Pearson", 
  "Josh Robinson",
  "Kyle Carrington", 
  "Leon Khan", 
  "Luke Masters",
  "Niall Raymond", 
  "Ross Barney",
  "Seb Jennings",
  "Sohrob Rostampour", 
  "Tom Kelton", 
  "Tom Wright", 
  "Will Allsopp",
  "Zach Murphy",
  "Zak Waddington"
];
