const defaultPlayers = [
  "Ash Hind",
  "Bailey Fulton", 
  "Ben Attle", 
  "Ben Franks",
  "Bradley Travis", 
  "Chad Ogden", 
  "Craig Ingham", 
  "Danny Minshull", 
  "Dom Johnson", 
  "Jake Halstead",
  "James Shooter", 
  "Joe Duffy", 
  "Joe Kinnear", 
  "Joe Rawlins", 
  "John Sheard (Shed)", 
  "Jorge Westin-Pearson", 
  "Josh Robinson",
  "Kieren Keogh",
  "Kyle Carrington", 
  "Leon Khan", 
  "Luke Masters",
  "Matty Carysforth",
  "Niall Raymond",
  "Reece Kendall",
  "Ross Barney",
  "Seb Jennings",
  "Sohrob Rostampour", 
  "Tom Kelton", 
  "Tom Wright", 
  "Trevor Jones",
  "Will Allsopp",
  "Zach Murphy",
  "Zak Waddington"
];
