name: Proxy Dispatch

on:
  repository_dispatch:
    types: [proxy-dispatch]

jobs:
  proxy-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Password Hash
        run: |
          if [ "${{ github.event.client_payload.passwordHash }}" != "1537491982" ]; then
            echo "Invalid password hash"
            exit 1
          fi
      - name: Trigger Update Data Dispatch
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d "{\"event_type\":\"update-data\",\"client_payload\":{\"players\":${{ toJson(github.event.client_payload.players) }},\"matches\":${{ toJson(github.event.client_payload.matches) }}}}"
