name: Update Data

on:
  workflow_dispatch:
    inputs:
      players:
        description: 'Updated players data'
        required: true
      matches:
        description: 'Updated matches data'
        required: true

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Update data.json
        env:
          PLAYERS_JSON: ${{ inputs.players }}
          MATCHES_JSON: ${{ inputs.matches }}
        run: |
          node -e "
            const fs = require('fs');
            const players = JSON.parse(process.env.PLAYERS_JSON);
            const matches = JSON.parse(process.env.MATCHES_JSON);
            fs.writeFileSync('data.json', JSON.stringify({ players, matches }, null, 2));
          "
          cat data.json
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data.json
          git commit -m 'Update data.json via workflow_dispatch' || echo "Nothing to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
