name: Update Data

on:
  workflow_dispatch:
    inputs:
      players:
        description: 'Updated players data'
        required: true
      matches:
        description: 'Updated matches data'
        required: true

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Update data.json
        run: |
          echo "Inputs received: players=${{ inputs.players }}"
          echo "Inputs received: matches=${{ inputs.matches }}"
          # Validate JSON inputs
          echo "${{ inputs.players }}" | jq . > /dev/null || { echo "Invalid players JSON"; exit 1; }
          echo "${{ inputs.matches }}" | jq . > /dev/null || { echo "Invalid matches JSON"; exit 1; }
          # Write JSON to data.json using printf to handle quotes
          printf '{"players": %s, "matches": %s}' "${{ inputs.players }}" "${{ inputs.matches }}" > data.json
          cat data.json
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data.json
          git commit -m 'Update data.json via workflow_dispatch' || echo "Nothing to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
